import ibm_db

# Connect to DB2
dsn_hostname = "2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud"
dsn_uid = "prg79418"        
dsn_pwd = "QOKWifsXGuPcg5Li"      
dsn_port = "30756"                
dsn_database = "bludb"            
dsn_driver = "{IBM DB2 ODBC DRIVER}"       
dsn_protocol = "TCPIP"           
dsn_security = "SSL"              

dsn = (
    "DRIVER={0};"
    "DATABASE={1};"
    "HOSTNAME={2};"
    "PORT={3};"
    "PROTOCOL={4};"
    "UID={5};"
    "PWD={6};"
    "SECURITY={7};"
).format(dsn_driver, dsn_database, dsn_hostname, dsn_port, dsn_protocol, dsn_uid, dsn_pwd, dsn_security)

create_dim_review_table = '''
    CREATE TABLE DimReview (
        id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
        product_id VARCHAR(20),
        rating_average REAL,
        reviews_count INT,
        count_1_star INT,
        percent_1_star REAL,
        count_2_star INT,
        percent_2_star REAL,
        count_3_star INT,
        percent_3_star REAL,
        count_4_star INT,
        percent_4_star REAL,
        count_5_star INT,
        percent_5_star REAL,
        PRIMARY KEY(id)
    );
'''

def main():
    
    ibm_conn = ibm_db.connect(dsn, "", "")

    ibm_db.exec_immediate(ibm_conn, """DROP TABLE IF EXISTS DimReview;""")
    ibm_db.exec_immediate(ibm_conn, create_dim_review_table)

    ibm_db.close(ibm_conn)

if __name__ == '__main__':
    main()